const fixedData = [
    {
        name: 'Microagulhamento',
        id: 4,
        value: 500,
        inCash: 100,
        parcel: 150,
    },
    {
        name: 'Fio Liso Agulhado',
        id: 19,
        value: 335,
        inCash: 100,
        parcel: 120,
    },
    {
        name: 'Fio de Tração Especulado',
        id: 20,
        value: 600,
        inCash: 200,
        parcel: 250,
    },
    {
        name: 'Fios Múltiplos',
        id: 23,
        value: 1000,
        inCash: 250,
        parcel: 300,
    },
    {
        name: 'Fio Liso Parafuso Agulhado',
        id: 21,
        value: 350,
        inCash: 100,
        parcel: 120,
    },
    {
        name: 'Fio Sculpt',
        id: 22,
        value: 900,
        inCash: 250,
        parcel: 300,
    },
    {
        name: 'Skinbooster',
        id: 7,
        value: 700,
        inCash: 225,
        parcel: 270,
    },
    {
        name: 'Preenchedor Rennova Plus Lido',
        id: 9,
        value: 1450,
        inCash: 500,
        parcel: 700,
    },
    {
        name: 'Preenchedor Rennova Ultra Volume',
        id: 10,
        value: 2400,
        inCash: 500,
        parcel: 700,
    },
    {
        name: 'Preenchedor Ultra Volume Plus',
        id: 11,
        value: 1600,
        inCash: 500,
        parcel: 700,
    },
    {
        name: 'Preenchedor Volume',
        id: 12,
        value: 1700,
        inCash: 500,
        parcel: 700,
    },
    {
        name: 'Preenchedor Volume Filler',
        id: 13,
        value: 1400,
        inCash: 500,
        parcel: 700,
    },
    {
        name: 'Toxina Botulínica (BOTOX)',
        id: 14,
        value: 30,
        inCash: 9,
        parcel: 15,
    },
    {
        name: 'Bioestimulador DIAMOND',
        id: 15,
        value: 3200,
        inCash: 350,
        parcel: 500,
    },
    {
        name: 'Bioestimulador ELEVA',
        id: 16,
        value: 3900,
        inCash: 999,
        parcel: 1200,
    },
    {
        name: 'Bioestimulador RADIESSE',
        id: 17,
        value: 3600,
        inCash: 999,
        parcel: 1200,
    },
    {
        name: 'Bioestimulador BIOMETIL',
        id: 18,
        value: 3900,
        inCash: 600,
        parcel: 1200,
    },

];

export default fixedData