const products = [
    {
        name: 'Microagulhamento',
        id: 4,
        price: 500,
        inCash: 100,
        parcel: 150,
    },
    {
        name: 'Fio Liso Agulhado',
        id: 19,
        price: 335,
        inCash: 100,
        parcel: 120,
    },
    {
        name: 'Fio de Tração Especulado',
        id: 20,
        price: 600,
        inCash: 200,
        parcel: 250,
    },
    {
        name: 'Fios Múltiplos',
        id: 23,
        price: 1000,
        inCash: 250,
        parcel: 300,
    },
    {
        name: 'Fio Liso Parafuso Agulhado',
        id: 21,
        price: 350,
        inCash: 100,
        parcel: 120,
    },
    {
        name: 'Fio Sculpt',
        id: 22,
        price: 900,
        inCash: 250,
        parcel: 300,
    },
    {
        name: 'Skinbooster',
        id: 7,
        price: 700,
        inCash: 225,
        parcel: 270,
    },
    {
        name: 'Preenchedor Rennova Plus Lido',
        id: 9,
        price: 1450,
        inCash: 500,
        parcel: 700,
    },
    {
        name: 'Preenchedor Rennova Ultra Volume',
        id: 10,
        price: 2400,
        inCash: 500,
        parcel: 700,
    },
    {
        name: 'Preenchedor Ultra Volume Plus',
        id: 11,
        price: 1600,
        inCash: 500,
        parcel: 700,
    },
    {
        name: 'Preenchedor Volume',
        id: 12,
        price: 1700,
        inCash: 500,
        parcel: 700,
    },
    {
        name: 'Preenchedor Volume Filler',
        id: 13,
        price: 1400,
        inCash: 500,
        parcel: 700,
    },
    {
        name: 'Toxina Botulínica (BOTOX)',
        id: 14,
        price: 30,
        inCash: 9,
        parcel: 15,
    },
    {
        name: 'Bioestimulador DIAMOND',
        id: 15,
        price: 3200,
        inCash: 350,
        parcel: 500,
    },
    {
        name: 'Bioestimulador ELEVA',
        id: 16,
        price: 3900,
        inCash: 999,
        parcel: 1200,
    },
    {
        name: 'Bioestimulador RADIESSE',
        id: 17,
        price: 3600,
        inCash: 999,
        parcel: 1200,
    },
    {
        name: 'Bioestimulador BIOMETIL',
        id: 18,
        price: 3900,
        inCash: 600,
        parcel: 1200,
    },
    {
        name: 'Bichectomia',
        id: 1,
        price: 700,
    },
    {
        name: 'Bleferosplatia',
        id: 2,
        price: 2000,
    },
    {
        name: 'Lipo de Papada Cirúrgica',
        id: 3,
        price: 1000,
    },
    {
        name: 'Brow lift (sem fio incluso)',
        id: 5,
        price: 2000,
    },
    {
        name: 'Lip Lifting',
        id: 6,
        price: 120,
    },
    {
        name: 'Vitalize Lips',
        id: 8,
        price: 120,
    },
    {
        name: 'Intradermoterapia',
        id: 24,
        price: 80,
    },
    {
        name: 'Lipo Enzimática',
        id: 25,
        price: 800,
    },
    {
        name: 'Ozonioterapia',
        id: 26,
        price: 100,
    },
    {
        name: 'Peeling',
        id: 27,
        price: 100,
    },
    {
        name: 'Depilação a Laser',
        id: 28,
        price: 69,
    },
];

export default products